on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: [self-hosted, backend-staging]
    steps:
      - name: Deploy Backend
        shell: bash
        run: |
          set -x
          echo "Deploying Backend..."
          export PATH=$PATH:/home/github-runner/.nvm/versions/node/v22.17.0/bin
          cd /var/www/backend-staging
          git checkout staging
          git pull origin staging
          timeout 300 npm install --verbose
          pm2 restart staging-backend
